sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rranjan14/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rranjan14/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-660276092212"
  bucket_path : "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
