sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rranjan14/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rranjan14/docker-react npm run test
